### ISSUE TITLE
Add "Numeric representation" to make LLD usable for different languages like Zabbix does it

### ISSUE THREAD

**Issue by xenadmin** [lxndrp/pdh2zabbix#1]
Hi! Very nice script. I come here via https://support.zabbix.com/browse/ZBXNEXT-1839
I tested it a little bit. Seems to work just fine. 
I use Perfmon to monitor several disk values. Sadly the servers I have to monitor have a language mix of en_US and de_DE and also different HDD counts. So LLD would be really nice. My problem is, that I have to use different names for the same perfmon tree of values. 
![grafik](https://user-images.githubusercontent.com/12057348/47287628-2cc9ec00-d5f3-11e8-8071-73c58b8a1b84.png)
Zabbix offers the ability to use numeric values as OS independent replacements, as you might know: https://www.zabbix.com/documentation/3.4/manual/config/items/perfcounters
Do you have the ability to offer something similar?
Otherwise I would just add a User Macro to my Hosts, which would replace the corresponding language value for the UserParameter. 
Thank you!

**Comment by lxndrp** [comment]
Unfortunately, the .NET API has no way of getting the counter IDs instead of the names – unless someone comes up with an example, or Microsoft enriches the corresponding .NET class [PerformanceCounter](https://docs.microsoft.com/de-de/dotnet/api/system.diagnostics.performancecounter?view=netframework-4.7.2), there is nothing I can do to implement this – sorry!
