### ISSUE TITLE
Failed on import to Zabbix with UTF-8 error & how to set up UserParameter in zabbix agent 2

### ISSUE THREAD

**Issue by Argon0** [lxndrp/pdh2zabbix#4]
2 quick things:
1) Import failed, for me 'cos the output was encoded in UTF16 LE BOM instead of UTF-8 though it mentions UTF-8 first thing in the file. So I opened it in Notepad++ and changed the encoding to UTF-8 and it imported fine.
2) NOW I have message from Zabbix "Unknown metric pdh2zbx.discovery" when I test the discovery rule. 
- I THINK this is due to no userparameters set up in Zabbix Agent's conf file, but am brand new to Zabbix so ... An example .conf file would be really useful...

**Comment by lxndrp** [comment]
The BOM problem should be fixed; I removed an unwanted \ufeff at the beginning of the PowerShell script (see https://github.com/lxndrp/pdh2zabbix/commit/5e21fbc02bf0f3d6c5c6fdaa9bd96e7f34317ef5).

Regarding the "Unknown metric" error, you *have* to setup a UserParameter in the agent config file, see [the Zabbix help pages on the topic](https://www.zabbix.com/documentation/current/en/manual/config/items/userparameters#example-1). I can't really give an example, because it depends on your setup, version, LLD name and PDH instance; you have to try it out. Maybe the [Zabbix Forum](https://www.zabbix.com/forum/) can guide you regarding the specifics.

HTH.
